### 회원가입

POST http://localhost:8080/sign-up
Content-Type: application/json

{
  "nickname": "모멘토",
  "email": "momento@momento.com",
  "password": "momento1234"
}


### 로그인

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "momento@momento.com",
  "password": "momento1234"
}


### 사용자 페이지

GET http://localhost:8080/user


### 관리자 페이지

GET http://localhost:8080/admin


### 메인 페이지

GET http://localhost:8080